=== zefang/model-driven-information-retrieval/SMILA.application/configuration/org.eclipse.smila.blackboard/schemas/RecordFilters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/***********************************************************************************************************************
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the accompanying
 * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors: Ivan Churkin (brox IT Solutions GmbH) - initial creator
 **********************************************************************************************************************/
-->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="Element">
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="Filter">
    <xs:sequence>
      <xs:element name="Element" type="Element" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>
  
  
  <xs:element name="RecordFilters">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Filter" type="Filter" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
</xs:schema>

=== zefang/model-driven-information-retrieval/SMILA.application/configuration/org.eclipse.smila.blackboard/RecordFilters.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  /***********************************************************************************************************************
  * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and 
  the accompanying
  * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies 
  this distribution,
  * and is available at http://www.eclipse.org/legal/epl-v10.html
  *
  * Contributors: Ivan Churkin (brox IT Solutions GmbH) - initial creator
  **********************************************************************************************************************/
-->
<RecordFilters xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schemas/RecordFilters.xsd">
  <Filter name="workflow-object">
    <Element name="MimeType" />
  </Filter>
  <Filter name="only-attributes">
    <Element name="*" />
  </Filter>
  <Filter name="no-filter">
    <Element name="*" />
  </Filter>
  <Filter name="nothing" />
</RecordFilters>
