=== zefang/model-driven-information-retrieval/org.eclipse.smila.connectivity.queue.worker/schemas/QueueWorkerConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/***********************************************************************************************************************
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the accompanying
 * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors: Ivan Churkin (brox IT Solutions GmbH) - initial creator
 **********************************************************************************************************************/
-->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.eclipse.org/smila/queue"
  xmlns="http://www.eclipse.org/smila/queue"
>

  <xs:complexType name="PropertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="Name" type="xs:string" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="BrokerConnectionType">
    <xs:sequence>
      <xs:element name="URL" type="xs:string"/>
      <xs:element name="User" type="xs:string"/>
      <xs:element name="Password" type="xs:string"/>
      <xs:element name="ConnectionFactory" type="xs:string"/>
      <xs:element name="ConnectionProperty" minOccurs="0" maxOccurs="unbounded" type="PropertyType"/>
    </xs:sequence>
    <xs:attribute name="Id" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="QueueConnectionType">
    <xs:attribute name="BrokerId" type="xs:string"/>
    <xs:attribute name="Queue" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="ProcessType">
    <xs:attribute name="Workflow" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="SendType">
    <xs:complexContent>
      <xs:extension base="QueueConnectionType">
        <xs:sequence>
          <xs:element name="SetProperty"  minOccurs="0" maxOccurs="unbounded" type="PropertyType"/>
        </xs:sequence>
        <xs:attribute name="RecordFilter" type="xs:string" use="optional"/>
        <xs:attribute name="PersistentDelivery" type="xs:boolean" use="optional" default="true"/>
        <xs:attribute name="WithAttachments" type="xs:boolean" use="optional" default="false"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="TaskListType" abstract="true">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:choice>
        <xs:element name="Process" type="ProcessType"/>
        <xs:element name="Send" type="SendType"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="BlackboardSync" type="xs:boolean" use="optional" default="true"/>
  </xs:complexType>
  
  <xs:complexType name="RouterTaskListType">
    <xs:complexContent>
      <xs:extension base="TaskListType"/>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="ListenerTaskListType">
    <xs:complexContent>
      <xs:extension base="TaskListType">
        <xs:attribute name="InitiallySet" type="xs:boolean" use="optional" default="false"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="RecordRecyclerTaskListType">
    <xs:complexContent>
      <xs:extension base="TaskListType"/>
    </xs:complexContent>
  </xs:complexType>
  
  
  <xs:complexType name="BaseRuleType" abstract="true">
    <xs:attribute name="Name" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="RouterRuleType">
    <xs:complexContent>
      <xs:extension base="BaseRuleType">
        <xs:sequence>
          <xs:element name="Condition" type="xs:string"/>
          <xs:element name="Task" type="RouterTaskListType"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="ListenerRuleType">
    <xs:complexContent>
      <xs:extension base="BaseRuleType">
        <xs:sequence>
          <xs:element name="Source" type="QueueConnectionType"/>
          <xs:element name="Condition" type="xs:string"/>
          <xs:element name="Task" type="ListenerTaskListType"/>
        </xs:sequence>
        <xs:attribute name="Threads" type="xs:int" use="optional" default="1"/>
        <!-- timeout in seconds -->
        <xs:attribute name="WaitMessageTimeout" type="xs:int" use="optional" default="1"/>
		<xs:attribute name="MaxMessageBlockSize" type="xs:int" use="optional" default="1"/>        
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>


  <xs:complexType name="RecordRecyclerRuleType">
    <xs:complexContent>
      <xs:extension base="BaseRuleType">
        <xs:sequence>
          <xs:element name="Condition" type="xs:string"/>
          <xs:element name="Task" type="RecordRecyclerTaskListType"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  
    
  <!-- CONNECTIONS ROOT -->
  <xs:complexType name="ConnectionsConfigType">
    <xs:sequence>
      <xs:element name="ConnectionConfig" type="BrokerConnectionType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="QueueWorkerConnectionsConfig" type="ConnectionsConfigType"/>
  
  
  <!-- ROUTER ROOT -->
  <xs:complexType name="RouterConfigType">
    <xs:sequence>
      <xs:element name="Rule" type="RouterRuleType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="QueueWorkerRouterConfig" type="RouterConfigType"/>
  
  <!-- LISTENER ROOT -->
  <xs:complexType name="ListenerConfigType">
    <xs:sequence>
      <xs:element name="Rule" type="ListenerRuleType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="QueueWorkerListenerConfig" type="ListenerConfigType"/>
  
  <!-- RecordRecycler ROOT -->
  <xs:complexType  name="RecordRecyclerConfigType">
    <xs:sequence>
      <xs:element name="Rule" type="RecordRecyclerRuleType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="QueueWorkerRecordRecyclerJob" type="RecordRecyclerConfigType"/>
  
</xs:schema>

=== zefang/model-driven-information-retrieval/SMILA.application/configuration/org.eclipse.smila.connectivity.queue.worker.jms/QueueWorkerListenerConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/***********************************************************************************************************************
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the accompanying
 * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors: Ivan Churkin (brox IT Solutions GmbH) - initial creator
 **********************************************************************************************************************/
-->
<QueueWorkerListenerConfig xmlns="http://www.eclipse.org/smila/queue"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schemas/QueueWorkerConfig.xsd"
>

  <Rule Name="ADD Rule" WaitMessageTimeout="10" Threads="4" MaxMessageBlockSize="20">
    <Source BrokerId="broker1" Queue="SMILA.connectivity"/>
    <Condition>Operation='ADD' and NOT(DataSourceID LIKE '%feeds%') and NOT(DataSourceID LIKE '%xmldump%')</Condition>
    <Task>
      <Process Workflow="AddPipeline"/>
    </Task>
  </Rule>

  <Rule Name="Delete Rule" WaitMessageTimeout="10" Threads="2" MaxMessageBlockSize="20">
    <Source BrokerId="broker1" Queue="SMILA.connectivity"/>
    <Condition>Operation='DELETE'</Condition>
    <Task>
      <Process Workflow="DeletePipeline"/>
    </Task>
  </Rule>

  <Rule Name="ADD Feed Rule" WaitMessageTimeout="10" Threads="2" MaxMessageBlockSize="20">
    <Source BrokerId="broker1" Queue="SMILA.connectivity"/>
    <Condition>Operation='ADD' and DataSourceID LIKE '%feeds%'</Condition>
    <Task>
      <Process Workflow="AddFeedPipeline"/>
    </Task>
  </Rule>
    
 <Rule Name="XML Dump Splitter Rule" WaitMessageTimeout="10" Threads="2" MaxMessageBlockSize="1">
    <Source BrokerId="broker1" Queue="SMILA.connectivity"/>
    <Condition>Operation='ADD' and DataSourceID LIKE '%xmldump%' and NOT(isXmlSnippet='true')</Condition>
    <Task>
      <Process Workflow="XmlDumpSplitterPipeline"/>
    </Task>
  </Rule>    

 <Rule Name="XML Dump Add Rule" WaitMessageTimeout="10" Threads="4" MaxMessageBlockSize="20">
    <Source BrokerId="broker1" Queue="SMILA.connectivity"/>
    <Condition>Operation='ADD' and DataSourceID LIKE '%xmldump%' and isXmlSnippet='true'</Condition>
    <Task>
      <Process Workflow="XmlDumpAddPipeline"/>
    </Task>
  </Rule>    

    
</QueueWorkerListenerConfig>

=== zefang/model-driven-information-retrieval/org.eclipse.smila.connectivity.queue.worker.test/configuration/org.eclipse.smila.connectivity.queue.worker.jms/recyclers/Recycler1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/***********************************************************************************************************************
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the accompanying
 * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors: Ivan Churkin (brox IT Solutions GmbH) - initial creator
 **********************************************************************************************************************/
-->
<QueueWorkerRecordRecyclerJob xmlns="http://www.eclipse.org/smila/queue"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../schemas/QueueWorkerConfig.xsd"
>

  <Rule Name="First recycle Rule">
    <Condition>DataSourceID='myDataSource'</Condition>
    <Task>
      <Send BrokerId="broker1" Queue="SMILA.connectivity" RecordFilter="nothing"/>
    </Task>
  </Rule>
  
  <Rule Name="Second recycle Rule">
    <Condition>NOT(DataSourceID='myDataSource')</Condition>
    <Task>
      <Send BrokerId="broker1" Queue="SMILA.connectivity" RecordFilter="nothing">
        <SetProperty Name="doAdd">no</SetProperty>
      </Send>
    </Task>
  </Rule>
  
</QueueWorkerRecordRecyclerJob>

=== zefang/model-driven-information-retrieval/org.eclipse.smila.connectivity.queue.worker.jms/QueueWorkerListenerConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/***********************************************************************************************************************
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the accompanying
 * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors: Ivan Churkin (brox IT Solutions GmbH) - initial creator
 **********************************************************************************************************************/
-->
<QueueWorkerListenerConfig xmlns="http://www.eclipse.org/smila/queue"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schemas/QueueWorkerConfig.xsd"
>

  <Rule Name="Default ADD Rule" WaitMessageTimeout="10">
    <Source BrokerId="broker1" Queue="queue1"/>
    <Condition>Operation='ADD' and someJMSProperty='someValue'</Condition>
    <Task>
      <Process Workflow="some-workflow"/>
      <Send BrokerId="broker2" Queue="queue2" RecordFilter="F2">
        <SetProperty Name="doAdd">yes</SetProperty>
        <SetProperty Name="doSomething">no</SetProperty>
      </Send>
    </Task>
  </Rule>
  
</QueueWorkerListenerConfig>
