=== zefang/model-driven-information-retrieval/org.eclipse.smila.lucene/schemas/Mappings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/***********************************************************************************************************************
 * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. All rights reserved. This program and the accompanying
 * materials are made available under the terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors: Stucky (empolis GmbH) - initial API and implementation
 **********************************************************************************************************************/
-->
<xs:schema
  targetNamespace="http://www.eclipse.org/smila/lucene"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns="http://www.eclipse.org/smila/lucene"
>
  
  <xs:element name="Mappings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Mapping" type="Mapping" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="Mapping">
    <xs:sequence>
      <xs:element name="Attributes" type="Attributes"/>
      <xs:element name="Attachments" type="Attachments"/>
    </xs:sequence>
    <xs:attribute name="indexName" type="xs:string" use="required"/>
  </xs:complexType>
  
  <xs:complexType name="Attributes">
    <xs:sequence>
      <xs:element name="Attribute" type="Attribute" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Attachments">
    <xs:sequence>
      <xs:element name="Attachment" type="Attachment" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="Metadata" abstract="true">
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="fieldNo" type="xs:int"  use="required"/>
  </xs:complexType>
  
  <xs:complexType name="Attribute">
    <xs:complexContent>
      <xs:extension base="Metadata"/>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="Attachment">
    <xs:complexContent>
      <xs:extension base="Metadata"/>
    </xs:complexContent>
  </xs:complexType>
  
</xs:schema>

=== zefang/model-driven-information-retrieval/org.eclipse.smila.connectivity.queue.worker.test/configuration/org.eclipse.smila.lucene/Mappings.xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- 
  * Copyright (c) 2008 empolis GmbH and brox IT Solutions GmbH. 
  * All rights reserved. This program and the accompanying materials
  * are made available under the terms of the Eclipse Public License v1.0
  * which accompanies this distribution, and is available at
  * http://www.eclipse.org/legal/epl-v10.html
  *
  * Contributors:
  *    Daniel Stucky (empolis GmbH) - initial design
-->
<Mappings xmlns="http://www.eclipse.org/smila/lucene"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="schemas/Mappings.xsd"
>
  <Mapping indexName="test_index">
    <Attributes>
      <Attribute name="Filename" fieldNo="1" />
      <Attribute name="Path" fieldNo="2" />    
    <Attribute name="LastModifiedDate" fieldNo="3" />
    <Attribute name="Url" fieldNo="4" />
    <Attribute name="Title" fieldNo="5" />    
    <Attribute name="Extension" fieldNo="6" />
    <Attribute name="Size" fieldNo="7" />
    <Attribute name="MimeType" fieldNo="8" />           
    </Attributes>
    <Attachments>
        <Attachment name="Text" fieldNo="0" />      
    </Attachments>
  </Mapping>
</Mappings>
